//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBMSDBEntities : DbContext
    {
        public BBMSDBEntities()
            : base("name=BBMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAdmin> tbAdmins { get; set; }
        public virtual DbSet<tbBloodBank> tbBloodBanks { get; set; }
        public virtual DbSet<tbBloodStock> tbBloodStocks { get; set; }
        public virtual DbSet<tbEventRegistration> tbEventRegistrations { get; set; }
        public virtual DbSet<tbEvent> tbEvents { get; set; }
        public virtual DbSet<tbHistory> tbHistories { get; set; }
        public virtual DbSet<tbNotification> tbNotifications { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
