//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBloodBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBloodBank()
        {
            this.tbBloodStocks = new HashSet<tbBloodStock>();
            this.tbEvents = new HashSet<tbEvent>();
        }
    
        public int BloodBankId { get; set; }
        public string BloodBankName { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public Nullable<int> Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBloodStock> tbBloodStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEvent> tbEvents { get; set; }
    }
}
