//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBloodStock
    {
        public int StockId { get; set; }
        public Nullable<int> BloodBankId { get; set; }
        public Nullable<int> A_Count { get; set; }
        public Nullable<int> B_Count { get; set; }
        public Nullable<int> O_Count { get; set; }
        public Nullable<int> AB_Count { get; set; }
        public Nullable<int> A_Count1 { get; set; }
        public Nullable<int> B_Count1 { get; set; }
        public Nullable<int> O_Count1 { get; set; }
        public Nullable<int> AB_Count1 { get; set; }
    
        public virtual tbBloodBank tbBloodBank { get; set; }
    }
}
